// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bengobox/auth-service/internal/ent/auditlog"
	"github.com/bengobox/auth-service/internal/ent/loginattempt"
	"github.com/bengobox/auth-service/internal/ent/oauthclient"
	"github.com/bengobox/auth-service/internal/ent/passwordresettoken"
	"github.com/bengobox/auth-service/internal/ent/schema"
	"github.com/bengobox/auth-service/internal/ent/session"
	"github.com/bengobox/auth-service/internal/ent/tenant"
	"github.com/bengobox/auth-service/internal/ent/tenantmembership"
	"github.com/bengobox/auth-service/internal/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[3].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescOccurredAt is the schema descriptor for occurred_at field.
	auditlogDescOccurredAt := auditlogFields[9].Descriptor()
	// auditlog.DefaultOccurredAt holds the default value on creation for the occurred_at field.
	auditlog.DefaultOccurredAt = auditlogDescOccurredAt.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	loginattemptFields := schema.LoginAttempt{}.Fields()
	_ = loginattemptFields
	// loginattemptDescEmail is the schema descriptor for email field.
	loginattemptDescEmail := loginattemptFields[3].Descriptor()
	// loginattempt.DefaultEmail holds the default value on creation for the email field.
	loginattempt.DefaultEmail = loginattemptDescEmail.Default.(string)
	// loginattemptDescSuccess is the schema descriptor for success field.
	loginattemptDescSuccess := loginattemptFields[6].Descriptor()
	// loginattempt.DefaultSuccess holds the default value on creation for the success field.
	loginattempt.DefaultSuccess = loginattemptDescSuccess.Default.(bool)
	// loginattemptDescOccurredAt is the schema descriptor for occurred_at field.
	loginattemptDescOccurredAt := loginattemptFields[8].Descriptor()
	// loginattempt.DefaultOccurredAt holds the default value on creation for the occurred_at field.
	loginattempt.DefaultOccurredAt = loginattemptDescOccurredAt.Default.(func() time.Time)
	// loginattemptDescID is the schema descriptor for id field.
	loginattemptDescID := loginattemptFields[0].Descriptor()
	// loginattempt.DefaultID holds the default value on creation for the id field.
	loginattempt.DefaultID = loginattemptDescID.Default.(func() uuid.UUID)
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescClientID is the schema descriptor for client_id field.
	oauthclientDescClientID := oauthclientFields[1].Descriptor()
	// oauthclient.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthclient.ClientIDValidator = oauthclientDescClientID.Validators[0].(func(string) error)
	// oauthclientDescName is the schema descriptor for name field.
	oauthclientDescName := oauthclientFields[3].Descriptor()
	// oauthclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	oauthclient.NameValidator = oauthclientDescName.Validators[0].(func(string) error)
	// oauthclientDescPublic is the schema descriptor for public field.
	oauthclientDescPublic := oauthclientFields[6].Descriptor()
	// oauthclient.DefaultPublic holds the default value on creation for the public field.
	oauthclient.DefaultPublic = oauthclientDescPublic.Default.(bool)
	// oauthclientDescCreatedAt is the schema descriptor for created_at field.
	oauthclientDescCreatedAt := oauthclientFields[9].Descriptor()
	// oauthclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthclient.DefaultCreatedAt = oauthclientDescCreatedAt.Default.(func() time.Time)
	// oauthclientDescUpdatedAt is the schema descriptor for updated_at field.
	oauthclientDescUpdatedAt := oauthclientFields[10].Descriptor()
	// oauthclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthclient.DefaultUpdatedAt = oauthclientDescUpdatedAt.Default.(func() time.Time)
	// oauthclient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthclient.UpdateDefaultUpdatedAt = oauthclientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthclientDescID is the schema descriptor for id field.
	oauthclientDescID := oauthclientFields[0].Descriptor()
	// oauthclient.DefaultID holds the default value on creation for the id field.
	oauthclient.DefaultID = oauthclientDescID.Default.(func() uuid.UUID)
	passwordresettokenFields := schema.PasswordResetToken{}.Fields()
	_ = passwordresettokenFields
	// passwordresettokenDescTokenHash is the schema descriptor for token_hash field.
	passwordresettokenDescTokenHash := passwordresettokenFields[2].Descriptor()
	// passwordresettoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	passwordresettoken.TokenHashValidator = passwordresettokenDescTokenHash.Validators[0].(func(string) error)
	// passwordresettokenDescCreatedAt is the schema descriptor for created_at field.
	passwordresettokenDescCreatedAt := passwordresettokenFields[5].Descriptor()
	// passwordresettoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordresettoken.DefaultCreatedAt = passwordresettokenDescCreatedAt.Default.(func() time.Time)
	// passwordresettokenDescID is the schema descriptor for id field.
	passwordresettokenDescID := passwordresettokenFields[0].Descriptor()
	// passwordresettoken.DefaultID holds the default value on creation for the id field.
	passwordresettoken.DefaultID = passwordresettokenDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescSessionType is the schema descriptor for session_type field.
	sessionDescSessionType := sessionFields[4].Descriptor()
	// session.DefaultSessionType holds the default value on creation for the session_type field.
	session.DefaultSessionType = sessionDescSessionType.Default.(string)
	// sessionDescStatus is the schema descriptor for status field.
	sessionDescStatus := sessionFields[5].Descriptor()
	// session.DefaultStatus holds the default value on creation for the status field.
	session.DefaultStatus = sessionDescStatus.Default.(string)
	// sessionDescRefreshTokenHash is the schema descriptor for refresh_token_hash field.
	sessionDescRefreshTokenHash := sessionFields[6].Descriptor()
	// session.RefreshTokenHashValidator is a validator for the "refresh_token_hash" field. It is called by the builders before save.
	session.RefreshTokenHashValidator = sessionDescRefreshTokenHash.Validators[0].(func(string) error)
	// sessionDescIssuedAt is the schema descriptor for issued_at field.
	sessionDescIssuedAt := sessionFields[7].Descriptor()
	// session.DefaultIssuedAt holds the default value on creation for the issued_at field.
	session.DefaultIssuedAt = sessionDescIssuedAt.Default.(func() time.Time)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[14].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[15].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[2].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescStatus is the schema descriptor for status field.
	tenantDescStatus := tenantFields[3].Descriptor()
	// tenant.DefaultStatus holds the default value on creation for the status field.
	tenant.DefaultStatus = tenantDescStatus.Default.(string)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[5].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[6].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	tenantmembershipFields := schema.TenantMembership{}.Fields()
	_ = tenantmembershipFields
	// tenantmembershipDescStatus is the schema descriptor for status field.
	tenantmembershipDescStatus := tenantmembershipFields[4].Descriptor()
	// tenantmembership.DefaultStatus holds the default value on creation for the status field.
	tenantmembership.DefaultStatus = tenantmembershipDescStatus.Default.(string)
	// tenantmembershipDescCreatedAt is the schema descriptor for created_at field.
	tenantmembershipDescCreatedAt := tenantmembershipFields[5].Descriptor()
	// tenantmembership.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantmembership.DefaultCreatedAt = tenantmembershipDescCreatedAt.Default.(func() time.Time)
	// tenantmembershipDescUpdatedAt is the schema descriptor for updated_at field.
	tenantmembershipDescUpdatedAt := tenantmembershipFields[6].Descriptor()
	// tenantmembership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantmembership.DefaultUpdatedAt = tenantmembershipDescUpdatedAt.Default.(func() time.Time)
	// tenantmembership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenantmembership.UpdateDefaultUpdatedAt = tenantmembershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantmembershipDescID is the schema descriptor for id field.
	tenantmembershipDescID := tenantmembershipFields[0].Descriptor()
	// tenantmembership.DefaultID holds the default value on creation for the id field.
	tenantmembership.DefaultID = tenantmembershipDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[3].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescPrimaryTenantID is the schema descriptor for primary_tenant_id field.
	userDescPrimaryTenantID := userFields[6].Descriptor()
	// user.PrimaryTenantIDValidator is a validator for the "primary_tenant_id" field. It is called by the builders before save.
	user.PrimaryTenantIDValidator = userDescPrimaryTenantID.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
