// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-service/internal/ent/predicate"
	"github.com/bengobox/auth-service/internal/ent/tenant"
	"github.com/bengobox/auth-service/internal/ent/tenantmembership"
	"github.com/bengobox/auth-service/internal/ent/user"
	"github.com/google/uuid"
)

// TenantMembershipUpdate is the builder for updating TenantMembership entities.
type TenantMembershipUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMembershipMutation
}

// Where appends a list predicates to the TenantMembershipUpdate builder.
func (_u *TenantMembershipUpdate) Where(ps ...predicate.TenantMembership) *TenantMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TenantMembershipUpdate) SetUserID(v uuid.UUID) *TenantMembershipUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantMembershipUpdate) SetNillableUserID(v *uuid.UUID) *TenantMembershipUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantMembershipUpdate) SetTenantID(v uuid.UUID) *TenantMembershipUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantMembershipUpdate) SetNillableTenantID(v *uuid.UUID) *TenantMembershipUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetRoles sets the "roles" field.
func (_u *TenantMembershipUpdate) SetRoles(v []string) *TenantMembershipUpdate {
	_u.mutation.SetRoles(v)
	return _u
}

// AppendRoles appends value to the "roles" field.
func (_u *TenantMembershipUpdate) AppendRoles(v []string) *TenantMembershipUpdate {
	_u.mutation.AppendRoles(v)
	return _u
}

// ClearRoles clears the value of the "roles" field.
func (_u *TenantMembershipUpdate) ClearRoles() *TenantMembershipUpdate {
	_u.mutation.ClearRoles()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantMembershipUpdate) SetStatus(v string) *TenantMembershipUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantMembershipUpdate) SetNillableStatus(v *string) *TenantMembershipUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantMembershipUpdate) SetUpdatedAt(v time.Time) *TenantMembershipUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TenantMembershipUpdate) SetUser(v *User) *TenantMembershipUpdate {
	return _u.SetUserID(v.ID)
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantMembershipUpdate) SetTenant(v *Tenant) *TenantMembershipUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantMembershipMutation object of the builder.
func (_u *TenantMembershipUpdate) Mutation() *TenantMembershipMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TenantMembershipUpdate) ClearUser() *TenantMembershipUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantMembershipUpdate) ClearTenant() *TenantMembershipUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantMembershipUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantMembershipUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantmembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantMembershipUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantMembership.user"`)
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantMembership.tenant"`)
	}
	return nil
}

func (_u *TenantMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantmembership.Table, tenantmembership.Columns, sqlgraph.NewFieldSpec(tenantmembership.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Roles(); ok {
		_spec.SetField(tenantmembership.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenantmembership.FieldRoles, value)
		})
	}
	if _u.mutation.RolesCleared() {
		_spec.ClearField(tenantmembership.FieldRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantmembership.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantmembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmembership.UserTable,
			Columns: []string{tenantmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmembership.UserTable,
			Columns: []string{tenantmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmembership.TenantTable,
			Columns: []string{tenantmembership.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmembership.TenantTable,
			Columns: []string{tenantmembership.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantMembershipUpdateOne is the builder for updating a single TenantMembership entity.
type TenantMembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMembershipMutation
}

// SetUserID sets the "user_id" field.
func (_u *TenantMembershipUpdateOne) SetUserID(v uuid.UUID) *TenantMembershipUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantMembershipUpdateOne) SetNillableUserID(v *uuid.UUID) *TenantMembershipUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantMembershipUpdateOne) SetTenantID(v uuid.UUID) *TenantMembershipUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantMembershipUpdateOne) SetNillableTenantID(v *uuid.UUID) *TenantMembershipUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetRoles sets the "roles" field.
func (_u *TenantMembershipUpdateOne) SetRoles(v []string) *TenantMembershipUpdateOne {
	_u.mutation.SetRoles(v)
	return _u
}

// AppendRoles appends value to the "roles" field.
func (_u *TenantMembershipUpdateOne) AppendRoles(v []string) *TenantMembershipUpdateOne {
	_u.mutation.AppendRoles(v)
	return _u
}

// ClearRoles clears the value of the "roles" field.
func (_u *TenantMembershipUpdateOne) ClearRoles() *TenantMembershipUpdateOne {
	_u.mutation.ClearRoles()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantMembershipUpdateOne) SetStatus(v string) *TenantMembershipUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantMembershipUpdateOne) SetNillableStatus(v *string) *TenantMembershipUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantMembershipUpdateOne) SetUpdatedAt(v time.Time) *TenantMembershipUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TenantMembershipUpdateOne) SetUser(v *User) *TenantMembershipUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantMembershipUpdateOne) SetTenant(v *Tenant) *TenantMembershipUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantMembershipMutation object of the builder.
func (_u *TenantMembershipUpdateOne) Mutation() *TenantMembershipMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TenantMembershipUpdateOne) ClearUser() *TenantMembershipUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantMembershipUpdateOne) ClearTenant() *TenantMembershipUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the TenantMembershipUpdate builder.
func (_u *TenantMembershipUpdateOne) Where(ps ...predicate.TenantMembership) *TenantMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantMembershipUpdateOne) Select(field string, fields ...string) *TenantMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantMembership entity.
func (_u *TenantMembershipUpdateOne) Save(ctx context.Context) (*TenantMembership, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantMembershipUpdateOne) SaveX(ctx context.Context) *TenantMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantMembershipUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantmembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantMembershipUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantMembership.user"`)
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantMembership.tenant"`)
	}
	return nil
}

func (_u *TenantMembershipUpdateOne) sqlSave(ctx context.Context) (_node *TenantMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantmembership.Table, tenantmembership.Columns, sqlgraph.NewFieldSpec(tenantmembership.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantmembership.FieldID)
		for _, f := range fields {
			if !tenantmembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantmembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Roles(); ok {
		_spec.SetField(tenantmembership.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenantmembership.FieldRoles, value)
		})
	}
	if _u.mutation.RolesCleared() {
		_spec.ClearField(tenantmembership.FieldRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantmembership.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantmembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmembership.UserTable,
			Columns: []string{tenantmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmembership.UserTable,
			Columns: []string{tenantmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmembership.TenantTable,
			Columns: []string{tenantmembership.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmembership.TenantTable,
			Columns: []string{tenantmembership.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenantMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
