// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-service/internal/ent/predicate"
	"github.com/bengobox/auth-service/internal/ent/user"
	"github.com/bengobox/auth-service/internal/ent/useridentity"
	"github.com/google/uuid"
)

// UserIdentityUpdate is the builder for updating UserIdentity entities.
type UserIdentityUpdate struct {
	config
	hooks    []Hook
	mutation *UserIdentityMutation
}

// Where appends a list predicates to the UserIdentityUpdate builder.
func (_u *UserIdentityUpdate) Where(ps ...predicate.UserIdentity) *UserIdentityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserIdentityUpdate) SetUserID(v uuid.UUID) *UserIdentityUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableUserID(v *uuid.UUID) *UserIdentityUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserIdentityUpdate) SetProvider(v string) *UserIdentityUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableProvider(v *string) *UserIdentityUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderSubject sets the "provider_subject" field.
func (_u *UserIdentityUpdate) SetProviderSubject(v string) *UserIdentityUpdate {
	_u.mutation.SetProviderSubject(v)
	return _u
}

// SetNillableProviderSubject sets the "provider_subject" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableProviderSubject(v *string) *UserIdentityUpdate {
	if v != nil {
		_u.SetProviderSubject(*v)
	}
	return _u
}

// SetProviderEmail sets the "provider_email" field.
func (_u *UserIdentityUpdate) SetProviderEmail(v string) *UserIdentityUpdate {
	_u.mutation.SetProviderEmail(v)
	return _u
}

// SetNillableProviderEmail sets the "provider_email" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableProviderEmail(v *string) *UserIdentityUpdate {
	if v != nil {
		_u.SetProviderEmail(*v)
	}
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *UserIdentityUpdate) SetEmailVerified(v bool) *UserIdentityUpdate {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableEmailVerified(v *bool) *UserIdentityUpdate {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UserIdentityUpdate) SetAccessToken(v string) *UserIdentityUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableAccessToken(v *string) *UserIdentityUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *UserIdentityUpdate) ClearAccessToken() *UserIdentityUpdate {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserIdentityUpdate) SetRefreshToken(v string) *UserIdentityUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableRefreshToken(v *string) *UserIdentityUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserIdentityUpdate) ClearRefreshToken() *UserIdentityUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *UserIdentityUpdate) SetTokenExpiry(v time.Time) *UserIdentityUpdate {
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableTokenExpiry(v *time.Time) *UserIdentityUpdate {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// ClearTokenExpiry clears the value of the "token_expiry" field.
func (_u *UserIdentityUpdate) ClearTokenExpiry() *UserIdentityUpdate {
	_u.mutation.ClearTokenExpiry()
	return _u
}

// SetScope sets the "scope" field.
func (_u *UserIdentityUpdate) SetScope(v string) *UserIdentityUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableScope(v *string) *UserIdentityUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *UserIdentityUpdate) ClearScope() *UserIdentityUpdate {
	_u.mutation.ClearScope()
	return _u
}

// SetProfile sets the "profile" field.
func (_u *UserIdentityUpdate) SetProfile(v map[string]interface{}) *UserIdentityUpdate {
	_u.mutation.SetProfile(v)
	return _u
}

// ClearProfile clears the value of the "profile" field.
func (_u *UserIdentityUpdate) ClearProfile() *UserIdentityUpdate {
	_u.mutation.ClearProfile()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserIdentityUpdate) SetUpdatedAt(v time.Time) *UserIdentityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserIdentityUpdate) SetUser(v *User) *UserIdentityUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserIdentityMutation object of the builder.
func (_u *UserIdentityUpdate) Mutation() *UserIdentityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserIdentityUpdate) ClearUser() *UserIdentityUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserIdentityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserIdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserIdentityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserIdentityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserIdentityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useridentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserIdentityUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := useridentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderSubject(); ok {
		if err := useridentity.ProviderSubjectValidator(v); err != nil {
			return &ValidationError{Name: "provider_subject", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderEmail(); ok {
		if err := useridentity.ProviderEmailValidator(v); err != nil {
			return &ValidationError{Name: "provider_email", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_email": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserIdentity.user"`)
	}
	return nil
}

func (_u *UserIdentityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useridentity.Table, useridentity.Columns, sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(useridentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSubject(); ok {
		_spec.SetField(useridentity.FieldProviderSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderEmail(); ok {
		_spec.SetField(useridentity.FieldProviderEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(useridentity.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(useridentity.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(useridentity.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(useridentity.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(useridentity.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(useridentity.FieldTokenExpiry, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiryCleared() {
		_spec.ClearField(useridentity.FieldTokenExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(useridentity.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(useridentity.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.Profile(); ok {
		_spec.SetField(useridentity.FieldProfile, field.TypeJSON, value)
	}
	if _u.mutation.ProfileCleared() {
		_spec.ClearField(useridentity.FieldProfile, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useridentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useridentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserIdentityUpdateOne is the builder for updating a single UserIdentity entity.
type UserIdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserIdentityMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserIdentityUpdateOne) SetUserID(v uuid.UUID) *UserIdentityUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableUserID(v *uuid.UUID) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserIdentityUpdateOne) SetProvider(v string) *UserIdentityUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableProvider(v *string) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderSubject sets the "provider_subject" field.
func (_u *UserIdentityUpdateOne) SetProviderSubject(v string) *UserIdentityUpdateOne {
	_u.mutation.SetProviderSubject(v)
	return _u
}

// SetNillableProviderSubject sets the "provider_subject" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableProviderSubject(v *string) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetProviderSubject(*v)
	}
	return _u
}

// SetProviderEmail sets the "provider_email" field.
func (_u *UserIdentityUpdateOne) SetProviderEmail(v string) *UserIdentityUpdateOne {
	_u.mutation.SetProviderEmail(v)
	return _u
}

// SetNillableProviderEmail sets the "provider_email" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableProviderEmail(v *string) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetProviderEmail(*v)
	}
	return _u
}

// SetEmailVerified sets the "email_verified" field.
func (_u *UserIdentityUpdateOne) SetEmailVerified(v bool) *UserIdentityUpdateOne {
	_u.mutation.SetEmailVerified(v)
	return _u
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableEmailVerified(v *bool) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetEmailVerified(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UserIdentityUpdateOne) SetAccessToken(v string) *UserIdentityUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableAccessToken(v *string) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *UserIdentityUpdateOne) ClearAccessToken() *UserIdentityUpdateOne {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserIdentityUpdateOne) SetRefreshToken(v string) *UserIdentityUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableRefreshToken(v *string) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserIdentityUpdateOne) ClearRefreshToken() *UserIdentityUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *UserIdentityUpdateOne) SetTokenExpiry(v time.Time) *UserIdentityUpdateOne {
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableTokenExpiry(v *time.Time) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// ClearTokenExpiry clears the value of the "token_expiry" field.
func (_u *UserIdentityUpdateOne) ClearTokenExpiry() *UserIdentityUpdateOne {
	_u.mutation.ClearTokenExpiry()
	return _u
}

// SetScope sets the "scope" field.
func (_u *UserIdentityUpdateOne) SetScope(v string) *UserIdentityUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableScope(v *string) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *UserIdentityUpdateOne) ClearScope() *UserIdentityUpdateOne {
	_u.mutation.ClearScope()
	return _u
}

// SetProfile sets the "profile" field.
func (_u *UserIdentityUpdateOne) SetProfile(v map[string]interface{}) *UserIdentityUpdateOne {
	_u.mutation.SetProfile(v)
	return _u
}

// ClearProfile clears the value of the "profile" field.
func (_u *UserIdentityUpdateOne) ClearProfile() *UserIdentityUpdateOne {
	_u.mutation.ClearProfile()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserIdentityUpdateOne) SetUpdatedAt(v time.Time) *UserIdentityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserIdentityUpdateOne) SetUser(v *User) *UserIdentityUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserIdentityMutation object of the builder.
func (_u *UserIdentityUpdateOne) Mutation() *UserIdentityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserIdentityUpdateOne) ClearUser() *UserIdentityUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserIdentityUpdate builder.
func (_u *UserIdentityUpdateOne) Where(ps ...predicate.UserIdentity) *UserIdentityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserIdentityUpdateOne) Select(field string, fields ...string) *UserIdentityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserIdentity entity.
func (_u *UserIdentityUpdateOne) Save(ctx context.Context) (*UserIdentity, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserIdentityUpdateOne) SaveX(ctx context.Context) *UserIdentity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserIdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserIdentityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserIdentityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useridentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserIdentityUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := useridentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderSubject(); ok {
		if err := useridentity.ProviderSubjectValidator(v); err != nil {
			return &ValidationError{Name: "provider_subject", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderEmail(); ok {
		if err := useridentity.ProviderEmailValidator(v); err != nil {
			return &ValidationError{Name: "provider_email", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_email": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserIdentity.user"`)
	}
	return nil
}

func (_u *UserIdentityUpdateOne) sqlSave(ctx context.Context) (_node *UserIdentity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useridentity.Table, useridentity.Columns, sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserIdentity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useridentity.FieldID)
		for _, f := range fields {
			if !useridentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useridentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(useridentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderSubject(); ok {
		_spec.SetField(useridentity.FieldProviderSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderEmail(); ok {
		_spec.SetField(useridentity.FieldProviderEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailVerified(); ok {
		_spec.SetField(useridentity.FieldEmailVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(useridentity.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(useridentity.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(useridentity.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(useridentity.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(useridentity.FieldTokenExpiry, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiryCleared() {
		_spec.ClearField(useridentity.FieldTokenExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(useridentity.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(useridentity.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.Profile(); ok {
		_spec.SetField(useridentity.FieldProfile, field.TypeJSON, value)
	}
	if _u.mutation.ProfileCleared() {
		_spec.ClearField(useridentity.FieldProfile, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useridentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserIdentity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useridentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
