// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/auth-service/internal/ent/user"
	"github.com/bengobox/auth-service/internal/ent/useridentity"
	"github.com/google/uuid"
)

// UserIdentityCreate is the builder for creating a UserIdentity entity.
type UserIdentityCreate struct {
	config
	mutation *UserIdentityMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserIdentityCreate) SetUserID(v uuid.UUID) *UserIdentityCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *UserIdentityCreate) SetProvider(v string) *UserIdentityCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetProviderSubject sets the "provider_subject" field.
func (_c *UserIdentityCreate) SetProviderSubject(v string) *UserIdentityCreate {
	_c.mutation.SetProviderSubject(v)
	return _c
}

// SetProviderEmail sets the "provider_email" field.
func (_c *UserIdentityCreate) SetProviderEmail(v string) *UserIdentityCreate {
	_c.mutation.SetProviderEmail(v)
	return _c
}

// SetEmailVerified sets the "email_verified" field.
func (_c *UserIdentityCreate) SetEmailVerified(v bool) *UserIdentityCreate {
	_c.mutation.SetEmailVerified(v)
	return _c
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableEmailVerified(v *bool) *UserIdentityCreate {
	if v != nil {
		_c.SetEmailVerified(*v)
	}
	return _c
}

// SetAccessToken sets the "access_token" field.
func (_c *UserIdentityCreate) SetAccessToken(v string) *UserIdentityCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableAccessToken(v *string) *UserIdentityCreate {
	if v != nil {
		_c.SetAccessToken(*v)
	}
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *UserIdentityCreate) SetRefreshToken(v string) *UserIdentityCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableRefreshToken(v *string) *UserIdentityCreate {
	if v != nil {
		_c.SetRefreshToken(*v)
	}
	return _c
}

// SetTokenExpiry sets the "token_expiry" field.
func (_c *UserIdentityCreate) SetTokenExpiry(v time.Time) *UserIdentityCreate {
	_c.mutation.SetTokenExpiry(v)
	return _c
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableTokenExpiry(v *time.Time) *UserIdentityCreate {
	if v != nil {
		_c.SetTokenExpiry(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *UserIdentityCreate) SetScope(v string) *UserIdentityCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableScope(v *string) *UserIdentityCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetProfile sets the "profile" field.
func (_c *UserIdentityCreate) SetProfile(v map[string]interface{}) *UserIdentityCreate {
	_c.mutation.SetProfile(v)
	return _c
}

// SetLinkedAt sets the "linked_at" field.
func (_c *UserIdentityCreate) SetLinkedAt(v time.Time) *UserIdentityCreate {
	_c.mutation.SetLinkedAt(v)
	return _c
}

// SetNillableLinkedAt sets the "linked_at" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableLinkedAt(v *time.Time) *UserIdentityCreate {
	if v != nil {
		_c.SetLinkedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserIdentityCreate) SetUpdatedAt(v time.Time) *UserIdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableUpdatedAt(v *time.Time) *UserIdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserIdentityCreate) SetID(v uuid.UUID) *UserIdentityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserIdentityCreate) SetNillableID(v *uuid.UUID) *UserIdentityCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserIdentityCreate) SetUser(v *User) *UserIdentityCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserIdentityMutation object of the builder.
func (_c *UserIdentityCreate) Mutation() *UserIdentityMutation {
	return _c.mutation
}

// Save creates the UserIdentity in the database.
func (_c *UserIdentityCreate) Save(ctx context.Context) (*UserIdentity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserIdentityCreate) SaveX(ctx context.Context) *UserIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserIdentityCreate) defaults() {
	if _, ok := _c.mutation.EmailVerified(); !ok {
		v := useridentity.DefaultEmailVerified
		_c.mutation.SetEmailVerified(v)
	}
	if _, ok := _c.mutation.LinkedAt(); !ok {
		v := useridentity.DefaultLinkedAt()
		_c.mutation.SetLinkedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := useridentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := useridentity.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserIdentityCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserIdentity.user_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UserIdentity.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := useridentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderSubject(); !ok {
		return &ValidationError{Name: "provider_subject", err: errors.New(`ent: missing required field "UserIdentity.provider_subject"`)}
	}
	if v, ok := _c.mutation.ProviderSubject(); ok {
		if err := useridentity.ProviderSubjectValidator(v); err != nil {
			return &ValidationError{Name: "provider_subject", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderEmail(); !ok {
		return &ValidationError{Name: "provider_email", err: errors.New(`ent: missing required field "UserIdentity.provider_email"`)}
	}
	if v, ok := _c.mutation.ProviderEmail(); ok {
		if err := useridentity.ProviderEmailValidator(v); err != nil {
			return &ValidationError{Name: "provider_email", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EmailVerified(); !ok {
		return &ValidationError{Name: "email_verified", err: errors.New(`ent: missing required field "UserIdentity.email_verified"`)}
	}
	if _, ok := _c.mutation.LinkedAt(); !ok {
		return &ValidationError{Name: "linked_at", err: errors.New(`ent: missing required field "UserIdentity.linked_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserIdentity.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserIdentity.user"`)}
	}
	return nil
}

func (_c *UserIdentityCreate) sqlSave(ctx context.Context) (*UserIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserIdentityCreate) createSpec() (*UserIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &UserIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useridentity.Table, sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(useridentity.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderSubject(); ok {
		_spec.SetField(useridentity.FieldProviderSubject, field.TypeString, value)
		_node.ProviderSubject = value
	}
	if value, ok := _c.mutation.ProviderEmail(); ok {
		_spec.SetField(useridentity.FieldProviderEmail, field.TypeString, value)
		_node.ProviderEmail = value
	}
	if value, ok := _c.mutation.EmailVerified(); ok {
		_spec.SetField(useridentity.FieldEmailVerified, field.TypeBool, value)
		_node.EmailVerified = value
	}
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(useridentity.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(useridentity.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := _c.mutation.TokenExpiry(); ok {
		_spec.SetField(useridentity.FieldTokenExpiry, field.TypeTime, value)
		_node.TokenExpiry = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(useridentity.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Profile(); ok {
		_spec.SetField(useridentity.FieldProfile, field.TypeJSON, value)
		_node.Profile = value
	}
	if value, ok := _c.mutation.LinkedAt(); ok {
		_spec.SetField(useridentity.FieldLinkedAt, field.TypeTime, value)
		_node.LinkedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useridentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.UserTable,
			Columns: []string{useridentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserIdentityCreateBulk is the builder for creating many UserIdentity entities in bulk.
type UserIdentityCreateBulk struct {
	config
	err      error
	builders []*UserIdentityCreate
}

// Save creates the UserIdentity entities in the database.
func (_c *UserIdentityCreateBulk) Save(ctx context.Context) ([]*UserIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserIdentityCreateBulk) SaveX(ctx context.Context) []*UserIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
