// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// LoginAttempt is the predicate function for loginattempt builders.
type LoginAttempt func(*sql.Selector)

// OAuthClient is the predicate function for oauthclient builders.
type OAuthClient func(*sql.Selector)

// PasswordResetToken is the predicate function for passwordresettoken builders.
type PasswordResetToken func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantMembership is the predicate function for tenantmembership builders.
type TenantMembership func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
