// Code generated by ent, DO NOT EDIT.

package useridentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/auth-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldUserID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldProvider, v))
}

// ProviderSubject applies equality check predicate on the "provider_subject" field. It's identical to ProviderSubjectEQ.
func ProviderSubject(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldProviderSubject, v))
}

// ProviderEmail applies equality check predicate on the "provider_email" field. It's identical to ProviderEmailEQ.
func ProviderEmail(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldProviderEmail, v))
}

// EmailVerified applies equality check predicate on the "email_verified" field. It's identical to EmailVerifiedEQ.
func EmailVerified(v bool) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldEmailVerified, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldAccessToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldRefreshToken, v))
}

// TokenExpiry applies equality check predicate on the "token_expiry" field. It's identical to TokenExpiryEQ.
func TokenExpiry(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldTokenExpiry, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldScope, v))
}

// LinkedAt applies equality check predicate on the "linked_at" field. It's identical to LinkedAtEQ.
func LinkedAt(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldLinkedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldUserID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderSubjectEQ applies the EQ predicate on the "provider_subject" field.
func ProviderSubjectEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldProviderSubject, v))
}

// ProviderSubjectNEQ applies the NEQ predicate on the "provider_subject" field.
func ProviderSubjectNEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldProviderSubject, v))
}

// ProviderSubjectIn applies the In predicate on the "provider_subject" field.
func ProviderSubjectIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldProviderSubject, vs...))
}

// ProviderSubjectNotIn applies the NotIn predicate on the "provider_subject" field.
func ProviderSubjectNotIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldProviderSubject, vs...))
}

// ProviderSubjectGT applies the GT predicate on the "provider_subject" field.
func ProviderSubjectGT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldProviderSubject, v))
}

// ProviderSubjectGTE applies the GTE predicate on the "provider_subject" field.
func ProviderSubjectGTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldProviderSubject, v))
}

// ProviderSubjectLT applies the LT predicate on the "provider_subject" field.
func ProviderSubjectLT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldProviderSubject, v))
}

// ProviderSubjectLTE applies the LTE predicate on the "provider_subject" field.
func ProviderSubjectLTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldProviderSubject, v))
}

// ProviderSubjectContains applies the Contains predicate on the "provider_subject" field.
func ProviderSubjectContains(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContains(FieldProviderSubject, v))
}

// ProviderSubjectHasPrefix applies the HasPrefix predicate on the "provider_subject" field.
func ProviderSubjectHasPrefix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasPrefix(FieldProviderSubject, v))
}

// ProviderSubjectHasSuffix applies the HasSuffix predicate on the "provider_subject" field.
func ProviderSubjectHasSuffix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasSuffix(FieldProviderSubject, v))
}

// ProviderSubjectEqualFold applies the EqualFold predicate on the "provider_subject" field.
func ProviderSubjectEqualFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEqualFold(FieldProviderSubject, v))
}

// ProviderSubjectContainsFold applies the ContainsFold predicate on the "provider_subject" field.
func ProviderSubjectContainsFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContainsFold(FieldProviderSubject, v))
}

// ProviderEmailEQ applies the EQ predicate on the "provider_email" field.
func ProviderEmailEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldProviderEmail, v))
}

// ProviderEmailNEQ applies the NEQ predicate on the "provider_email" field.
func ProviderEmailNEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldProviderEmail, v))
}

// ProviderEmailIn applies the In predicate on the "provider_email" field.
func ProviderEmailIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldProviderEmail, vs...))
}

// ProviderEmailNotIn applies the NotIn predicate on the "provider_email" field.
func ProviderEmailNotIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldProviderEmail, vs...))
}

// ProviderEmailGT applies the GT predicate on the "provider_email" field.
func ProviderEmailGT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldProviderEmail, v))
}

// ProviderEmailGTE applies the GTE predicate on the "provider_email" field.
func ProviderEmailGTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldProviderEmail, v))
}

// ProviderEmailLT applies the LT predicate on the "provider_email" field.
func ProviderEmailLT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldProviderEmail, v))
}

// ProviderEmailLTE applies the LTE predicate on the "provider_email" field.
func ProviderEmailLTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldProviderEmail, v))
}

// ProviderEmailContains applies the Contains predicate on the "provider_email" field.
func ProviderEmailContains(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContains(FieldProviderEmail, v))
}

// ProviderEmailHasPrefix applies the HasPrefix predicate on the "provider_email" field.
func ProviderEmailHasPrefix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasPrefix(FieldProviderEmail, v))
}

// ProviderEmailHasSuffix applies the HasSuffix predicate on the "provider_email" field.
func ProviderEmailHasSuffix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasSuffix(FieldProviderEmail, v))
}

// ProviderEmailEqualFold applies the EqualFold predicate on the "provider_email" field.
func ProviderEmailEqualFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEqualFold(FieldProviderEmail, v))
}

// ProviderEmailContainsFold applies the ContainsFold predicate on the "provider_email" field.
func ProviderEmailContainsFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContainsFold(FieldProviderEmail, v))
}

// EmailVerifiedEQ applies the EQ predicate on the "email_verified" field.
func EmailVerifiedEQ(v bool) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldEmailVerified, v))
}

// EmailVerifiedNEQ applies the NEQ predicate on the "email_verified" field.
func EmailVerifiedNEQ(v bool) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldEmailVerified, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenIsNil applies the IsNil predicate on the "access_token" field.
func AccessTokenIsNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIsNull(FieldAccessToken))
}

// AccessTokenNotNil applies the NotNil predicate on the "access_token" field.
func AccessTokenNotNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotNull(FieldAccessToken))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContainsFold(FieldAccessToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenIsNil applies the IsNil predicate on the "refresh_token" field.
func RefreshTokenIsNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIsNull(FieldRefreshToken))
}

// RefreshTokenNotNil applies the NotNil predicate on the "refresh_token" field.
func RefreshTokenNotNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotNull(FieldRefreshToken))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContainsFold(FieldRefreshToken, v))
}

// TokenExpiryEQ applies the EQ predicate on the "token_expiry" field.
func TokenExpiryEQ(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldTokenExpiry, v))
}

// TokenExpiryNEQ applies the NEQ predicate on the "token_expiry" field.
func TokenExpiryNEQ(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldTokenExpiry, v))
}

// TokenExpiryIn applies the In predicate on the "token_expiry" field.
func TokenExpiryIn(vs ...time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldTokenExpiry, vs...))
}

// TokenExpiryNotIn applies the NotIn predicate on the "token_expiry" field.
func TokenExpiryNotIn(vs ...time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldTokenExpiry, vs...))
}

// TokenExpiryGT applies the GT predicate on the "token_expiry" field.
func TokenExpiryGT(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldTokenExpiry, v))
}

// TokenExpiryGTE applies the GTE predicate on the "token_expiry" field.
func TokenExpiryGTE(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldTokenExpiry, v))
}

// TokenExpiryLT applies the LT predicate on the "token_expiry" field.
func TokenExpiryLT(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldTokenExpiry, v))
}

// TokenExpiryLTE applies the LTE predicate on the "token_expiry" field.
func TokenExpiryLTE(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldTokenExpiry, v))
}

// TokenExpiryIsNil applies the IsNil predicate on the "token_expiry" field.
func TokenExpiryIsNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIsNull(FieldTokenExpiry))
}

// TokenExpiryNotNil applies the NotNil predicate on the "token_expiry" field.
func TokenExpiryNotNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotNull(FieldTokenExpiry))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeIsNil applies the IsNil predicate on the "scope" field.
func ScopeIsNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIsNull(FieldScope))
}

// ScopeNotNil applies the NotNil predicate on the "scope" field.
func ScopeNotNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotNull(FieldScope))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldContainsFold(FieldScope, v))
}

// ProfileIsNil applies the IsNil predicate on the "profile" field.
func ProfileIsNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIsNull(FieldProfile))
}

// ProfileNotNil applies the NotNil predicate on the "profile" field.
func ProfileNotNil() predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotNull(FieldProfile))
}

// LinkedAtEQ applies the EQ predicate on the "linked_at" field.
func LinkedAtEQ(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldLinkedAt, v))
}

// LinkedAtNEQ applies the NEQ predicate on the "linked_at" field.
func LinkedAtNEQ(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldLinkedAt, v))
}

// LinkedAtIn applies the In predicate on the "linked_at" field.
func LinkedAtIn(vs ...time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldLinkedAt, vs...))
}

// LinkedAtNotIn applies the NotIn predicate on the "linked_at" field.
func LinkedAtNotIn(vs ...time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldLinkedAt, vs...))
}

// LinkedAtGT applies the GT predicate on the "linked_at" field.
func LinkedAtGT(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldLinkedAt, v))
}

// LinkedAtGTE applies the GTE predicate on the "linked_at" field.
func LinkedAtGTE(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldLinkedAt, v))
}

// LinkedAtLT applies the LT predicate on the "linked_at" field.
func LinkedAtLT(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldLinkedAt, v))
}

// LinkedAtLTE applies the LTE predicate on the "linked_at" field.
func LinkedAtLTE(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldLinkedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserIdentity {
	return predicate.UserIdentity(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserIdentity {
	return predicate.UserIdentity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserIdentity {
	return predicate.UserIdentity(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserIdentity) predicate.UserIdentity {
	return predicate.UserIdentity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserIdentity) predicate.UserIdentity {
	return predicate.UserIdentity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserIdentity) predicate.UserIdentity {
	return predicate.UserIdentity(sql.NotPredicates(p))
}
